return {
  { import = "plugins.lsp" },
  { import = "plugins.formatting" },
  { import = "plugins.ui" },
  { import = "plugins.image" },
  { import = "plugins.latex" },
  { import = "plugins.markdown" },
  { import = "plugins.merge" },
  { import = "plugins.git" },
  { import = "plugins.mini" },
  { import = "plugins.treesitter" },
  { import = "plugins.copilot" },
  { import = "plugins.diagnostics" },
  { import = "plugins.mason" },
  { import = "plugins.dap" },
  { import = "plugins.rust" },
  { import = "plugins.misc" },
}
