return {
  {
    'folke/which-key.nvim',
    event = 'VimEnter',
    opts = {
      delay = 0,
      icons = { mappings = false, rules = false },
      spec = {
        { '<leader>b', group = 'Buffers' },
        { '<leader>e', desc = 'File explorer' },
        { '<leader>E', desc = 'File explorer (cwd)' },
        { '<leader>f', group = 'Find' },
        { '<leader>s', group = 'Search' },
        { '<leader>t', group = 'Tabs & terminal' },
        { '<leader>th', desc = 'Toggle horizontal terminal' },
        { '<leader>tv', desc = 'Toggle vertical terminal' },
        { '<leader>ti', desc = 'Toggle floating terminal' },
        { '<leader>ta', desc = 'Toggle all terminals' },
        { '<leader>ts', desc = 'Select terminal' },
        { '<Tab>', desc = 'Next buffer in tab' },
        { '<S-Tab>', desc = 'Previous buffer in tab' },
        { '<leader>1', desc = 'Buffer 1' },
        { '<leader>2', desc = 'Buffer 2' },
        { '<leader>3', desc = 'Buffer 3' },
        { '<leader>4', desc = 'Buffer 4' },
        { '<leader>5', desc = 'Buffer 5' },
        { '<leader>6', desc = 'Buffer 6' },
        { '<leader>7', desc = 'Buffer 7' },
        { '<leader>8', desc = 'Buffer 8' },
        { '<leader>9', desc = 'Buffer 9' },
        { '<C-h>', desc = 'Move to left window' },
        { '<C-j>', desc = 'Move to lower window' },
        { '<C-k>', desc = 'Move to upper window' },
        { '<C-l>', desc = 'Move to right window' },
      },
    },
  },
  {
    'RRethy/base16-nvim',
    lazy = false,
    priority = 1000,
    config = function()
      vim.cmd.colorscheme 'base16-gruvbox-material-dark-hard'
    end,
  },
}
